name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build DotNET35
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\src\Path of Diablo Launcher\Path of Diablo Launcher.vbproj" -property:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
      path: "$Env:GITHUB_WORKSPACE\src\Path of Diablo Launcher\bin\Release\Path of Diablo Launcher.exe"
